Juan carlos
indra-makers/g3-notifications-ms pull request #2
Opened 2022-05-16 12:49 UTC by jhcarlos8888

Correccion de codigo en modulo notificaciones

2022-05-16 13:07 UTC, caferrerbeam commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +public class NotificationsController {
borre los metodos...

2022-05-16 13:08 UTC, caferrerbeam commented on src/main/java/com/co/indra/coinmarketcap/notifications/repositories/UserNotificationsDataRepository.java
> +
tantas lineas en blanco....

2022-05-16 13:08 UTC, dernaut requested changes

2022-05-16 13:08 UTC, dernaut commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +    @PostMapping("/sendnotification")
No hace falta especificar el verbo, con la anotación POST se infiere que se está creando/enviando notificación

2022-05-16 13:08 UTC, dernaut commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +    @GetMapping("/searchnotificationID")
Aquí se busca por pathVariable (solo en el caso de buscar por id)

2022-05-16 13:08 UTC, dernaut commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +    @DeleteMapping
Para eliminar, se recomienda usar pathVariable (para envíar el id por link)

2022-05-16 13:08 UTC, dernaut commented on src/main/java/com/co/indra/coinmarketcap/notifications/model/entities/Notifications.java
> +    private Long id_notifications;
Eliminar snake case (usar camelcase)

2022-05-17 13:35 UTC, dernaut approved these changes

2022-05-17 13:35 UTC, dernaut commented on src/main/java/com/co/indra/coinmarketcap/notifications/model/entities/Notifications.java
> +	}
idNotifications

2022-05-17 13:35 UTC, dernaut commented on src/main/java/com/co/indra/coinmarketcap/notifications/model/entities/Notifications.java
> +	private Date sent_at;
sentAt

2022-05-17 14:44 UTC, titan9804 approved these changes

2022-05-17 14:46 UTC, JcontrerasV1997 approved these changes

2022-05-17 14:48 UTC, ZuluiZ approved these changes

2022-05-17 14:50 UTC, jhcarlos8888 reviewed
ok

2022-05-17 14:50 UTC, jhcarlos8888 commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +public class NotificationsController {
Metodos eliminados

2022-05-17 14:50 UTC, jhcarlos8888 commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +    @PostMapping("/sendnotification")
Verbo duplicado eliminado

2022-05-17 14:50 UTC, jhcarlos8888 commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +    @GetMapping("/searchnotificationID")
Se modifica busqueda por path variable segun el ID entregado

2022-05-17 14:50 UTC, jhcarlos8888 commented on src/main/java/com/co/indra/coinmarketcap/notifications/controllers/NotificationsController.java
> +    @DeleteMapping
Se modifica metodo para eliminar por medio del ID notitications

2022-05-17 14:50 UTC, jhcarlos8888 commented on src/main/java/com/co/indra/coinmarketcap/notifications/model/entities/Notifications.java
> +    private Long id_notifications;
Segun reunion se dejara Snake como usted lo indico

2022-05-17 14:50 UTC, jhcarlos8888 commented on src/main/java/com/co/indra/coinmarketcap/notifications/repositories/UserNotificationsDataRepository.java
> +
Se realiza correccion de identacion de todas las clases

2022-05-17 14:52 UTC, merged